'use client';
import React from 'react';

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { AntdRegistry } from '@ant-design/nextjs-registry';
import AppHeader from "@/components/AppHeader";
import { Layout } from 'antd';
import { Content } from 'antd/es/layout/layout';



import { usePathname } from 'next/navigation';
import AppSide, { AppSideMenu } from '@/components/AppSideMenu';

function IsRhPage() {
  const pathname = usePathname();
  return pathname.includes('/rh');
}



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AntdRegistry>
          <Layout  style={{ minHeight: '100vh' }}>
            <AppHeader />
            {IsRhPage() ? (
              <Layout hasSider>
                <AppSide />
                <Layout style={{marginLeft:"200px", marginTop:"100px"}}>
                  <Content style={{ padding: '16px', minHeight: 'calc(100vh - 64px)' }}>
                    {children}
                  </Content>
                  </Layout>
                </Layout>
                ) : (
                <Content style={{ padding: '16px', minHeight: 'calc(100vh - 64px)' }}>
                  {children}
                </Content>
            )}
              </Layout>
        </AntdRegistry>

      </body>
    </html>
  );
}
